"""ClinMira shared Python contract package placeholder."""

from .versions import (  # noqa: F401
    API_CONTRACT_VERSION,
    CONTRACT_VERSION_SET,
    FEATURE_FLAG_SNAPSHOT_CONTRACT_VERSION,
    FEATURE_FLAGS_CONTRACT_VERSION,
    HEALTH_CHECK_RESPONSE_CONTRACT_VERSION,
    HEALTH_CONTRACT_VERSION,
    OPENAPI_CONTRACT_VERSION,
)
