import type { SafetyRuleDefinition } from "./safety.dto"
import { SAFETY_RULESET_VERSION } from "./safety.dto"

export const PRE_ACTION_SAFETY_RULES: SafetyRuleDefinition[] = [
  {
    rule_key: "prompt_injection.ignore_previous_instructions",
    rule_version: SAFETY_RULESET_VERSION,
    category: "prompt_injection",
    severity: "critical",
    action: "block",
    message: "Prompt-injection attempt blocked before mock patient response.",
    text_patterns: [
      /ignore\s+(?:all\s+)?previous\s+instructions/i,
      /bypass\s+(?:safety\s+)?rules/i,
      /\bjailbreak\b/i,
      /\bdeveloper\s+message\b/i,
    ],
  },
  {
    rule_key: "hidden_fact.reveal_hidden_diagnosis",
    rule_version: SAFETY_RULESET_VERSION,
    category: "hidden_fact_request",
    severity: "critical",
    action: "block",
    message: "Hidden diagnosis or answer-key request blocked.",
    text_patterns: [
      /reveal\s+(?:the\s+)?hidden\s+diagnosis/i,
      /\bhidden\s+diagnosis\b/i,
      /\bactual\s+diagnosis\b/i,
      /\banswer\s+key\b/i,
      /\ball\s+hidden\s+facts\b/i,
    ],
  },
  {
    rule_key: "system_prompt.show_system_prompt",
    rule_version: SAFETY_RULESET_VERSION,
    category: "system_prompt_request",
    severity: "critical",
    action: "block",
    message: "System prompt or internal instruction request blocked.",
    text_patterns: [
      /show\s+(?:the\s+)?system\s+prompt/i,
      /\bsystem\s+prompt\b/i,
      /\binternal\s+instruction\b/i,
      /\bdeveloper\s+rule\b/i,
      /\bpolicy\s+text\b/i,
    ],
  },
  {
    rule_key: "faculty_notes.faculty_only_material",
    rule_version: SAFETY_RULESET_VERSION,
    category: "faculty_only_request",
    severity: "critical",
    action: "block",
    message: "Faculty-only material request blocked.",
    text_patterns: [
      /\bfaculty[-\s]?only\b/i,
      /\bfaculty\s+notes\b/i,
      /\binstructor[-\s]?only\b/i,
      /\bteacher[-\s]?only\b/i,
      /\bscoring\s+guide\b/i,
      /\brubric\s+says\b/i,
    ],
  },
  {
    rule_key: "role_escalation.admin_or_faculty",
    rule_version: SAFETY_RULESET_VERSION,
    category: "role_escalation",
    severity: "high",
    action: "block",
    message: "Role escalation attempt blocked.",
    text_patterns: [
      /\bact\s+as\s+(?:admin|faculty|instructor)\b/i,
      /\bpretend\s+you\s+are\s+(?:faculty|instructor|admin)\b/i,
      /\brole\s+override\b/i,
      /\badmin\s+override\b/i,
    ],
  },
  {
    rule_key: "hidden_fact.restricted_safety_or_evaluator_context",
    rule_version: SAFETY_RULESET_VERSION,
    category: "hidden_fact_request",
    severity: "critical",
    action: "block",
    message: "Restricted safety or evaluator context request blocked.",
    text_patterns: [
      /\bsafety[-\s]?only\s+fact\b/i,
      /\bguardrail\s+fact\b/i,
      /\bevaluator[-\s]?only\b/i,
      /\bevaluator\s+will\s+score\b/i,
      /\bscore\s+after\s+this\s+encounter\b/i,
    ],
  },
  {
    rule_key: "unsupported.diagnosis_certainty",
    rule_version: SAFETY_RULESET_VERSION,
    category: "unsupported_diagnosis",
    severity: "high",
    action: "block_unsupported",
    message: "Unsupported diagnosis certainty request blocked.",
    text_patterns: [
      /\bfinal\s+diagnosis\b/i,
      /\bexact\s+diagnosis\b/i,
      /\bdiagnos(?:e|is)\s+me\b/i,
      /\bwhat\s+do\s+i\s+have\b/i,
      /\bconfirmed\s+diagnosis\b/i,
      /\bdiagnosis\s+with\s+certainty\b/i,
    ],
  },
  {
    rule_key: "unsupported.treatment_plan",
    rule_version: SAFETY_RULESET_VERSION,
    category: "unsupported_treatment",
    severity: "high",
    action: "block_unsupported",
    message: "Unsupported treatment-plan request blocked.",
    text_patterns: [
      /\btreatment\s+plan\b/i,
      /\bstart\s+treatment\b/i,
      /\bhow\s+should\s+i\s+treat\b/i,
      /\bclinical\s+treatment\b/i,
      /\bprocedure\s+plan\b/i,
    ],
  },
  {
    rule_key: "unsupported.medication_recommendation",
    rule_version: SAFETY_RULESET_VERSION,
    category: "unsupported_medication",
    severity: "high",
    action: "block_unsupported",
    message: "Unsupported medication recommendation request blocked.",
    text_patterns: [
      /\bwhich\s+medication\b/i,
      /\bwhat\s+medication\b/i,
      /\bprescribe\b/i,
      /\bdosage\b/i,
      /\bdrug\s+recommendation\b/i,
      /\bantibiotic\b/i,
    ],
  },
  {
    rule_key: "unsupported.imaging_interpretation",
    rule_version: SAFETY_RULESET_VERSION,
    category: "unsupported_imaging",
    severity: "high",
    action: "block_unsupported",
    message: "Unsupported imaging interpretation request blocked.",
    text_patterns: [
      /\binterpret\s+(?:the\s+)?imaging\b/i,
      /\bimaging\s+finding\b/i,
      /\bx[-\s]?ray\b/i,
      /\bradiograph\b/i,
      /\bct\s+scan\b/i,
      /\bmri\b/i,
      /\bcbct\b/i,
    ],
  },
  {
    rule_key: "unsupported.debrief_generation",
    rule_version: SAFETY_RULESET_VERSION,
    category: "unsupported_debrief",
    severity: "high",
    action: "block_unsupported",
    message: "Unsupported debrief or scoring request blocked.",
    text_patterns: [
      /\bgenerate\s+(?:my\s+)?debrief\b/i,
      /\bdebrief\b/i,
      /\bwhat\s+did\s+i\s+miss\b/i,
      /\bscore\s+me\b/i,
      /\bgrade\s+me\b/i,
      /\brubric\b/i,
    ],
  },
  {
    rule_key: "risky_action.order_attempt",
    rule_version: SAFETY_RULESET_VERSION,
    category: "risky_action",
    severity: "critical",
    action: "block_unsupported",
    message: "Order attempts are unsupported in the mock simulation runtime.",
    action_types: ["order_attempt"],
  },
  {
    rule_key: "risky_action.diagnosis_attempt",
    rule_version: SAFETY_RULESET_VERSION,
    category: "risky_action",
    severity: "critical",
    action: "block_unsupported",
    message: "Diagnosis submission attempts are unsupported in the mock simulation runtime.",
    action_types: ["diagnosis_attempt"],
  },
  {
    rule_key: "risky_action.treatment_attempt",
    rule_version: SAFETY_RULESET_VERSION,
    category: "risky_action",
    severity: "critical",
    action: "block_unsupported",
    message: "Treatment attempts are unsupported in the mock simulation runtime.",
    action_types: ["treatment_attempt"],
  },
]

export const POST_RESPONSE_SAFETY_RULES: SafetyRuleDefinition[] = [
  {
    rule_key: "post_response.hidden_or_internal_leakage",
    rule_version: SAFETY_RULESET_VERSION,
    category: "hidden_fact_request",
    severity: "critical",
    action: "block",
    message: "Potential hidden or internal content leakage detected in mock response.",
    response_patterns: [
      /\bhidden\s+diagnosis\s*:/i,
      /\bfinal\s+diagnosis\s+is\b/i,
      /\bfaculty\s+note\s*:/i,
      /\bsystem\s+prompt\s*:/i,
      /\bdeveloper\s+message\s*:/i,
      /\binternal\s+instruction\s*:/i,
      /\bevaluator[-\s]?only\s*:/i,
      /\bsafety[-\s]?only\s*:/i,
    ],
  },
  {
    rule_key: "post_response.unsupported_treatment_or_medication",
    rule_version: SAFETY_RULESET_VERSION,
    category: "unsupported_treatment",
    severity: "critical",
    action: "block_unsupported",
    message: "Unsupported treatment or medication advice detected in mock response.",
    response_patterns: [
      /\btreatment\s+plan\s+is\b/i,
      /\bperform\s+root\s+canal\b/i,
      /\bextract\s+the\s+tooth\b/i,
      /\btake\s+amoxicillin\b/i,
      /\bstart\s+antibiotics\b/i,
      /\bprescribe\b/i,
      /\bdosage\b/i,
    ],
  },
  {
    rule_key: "post_response.unsupported_diagnosis_imaging_or_debrief",
    rule_version: SAFETY_RULESET_VERSION,
    category: "unsupported_diagnosis",
    severity: "high",
    action: "block_unsupported",
    message: "Unsupported diagnosis, imaging, or debrief claim detected in mock response.",
    response_patterns: [
      /\bconfirmed\s+diagnosis\b/i,
      /\bdefinitely\s+has\b/i,
      /\bradiograph\s+shows\b/i,
      /\bcbct\s+shows\b/i,
      /\bimaging\s+confirms\b/i,
      /\bdebrief\s*:/i,
      /\byou\s+missed\b/i,
      /\bscore\b/i,
    ],
  },
  {
    rule_key: "post_response.missing_fact_reference",
    rule_version: SAFETY_RULESET_VERSION,
    category: "fact_reference",
    severity: "medium",
    action: "warn",
    message: "Mock response appears to use a fact but has no fact reference.",
    requires_fact_reference: true,
  },
]
