import {
  Agent,
  AgentEvent,
  Case,
  ClinicalOrder,
  DebriefReport,
  FacultyMetric,
  ImagingStudy,
  PatientTwin,
  ReasoningNode,
  RubricItem,
  ScenarioDraft,
  SkillProgress,
  TimelineEvent,
  User,
} from "@/types"

export const currentUser: User = {
  id: "user-mohammad",
  name: "Mohammad Moradpoor",
  role: "Student",
  institution: "Demo University",
  program: "Dental Education",
  focusArea: "Clinical reasoning and treatment safety",
  avatarInitials: "MM",
  unreadNotifications: 4,
}

export const users: User[] = [
  currentUser,
  {
    id: "user-aylin",
    name: "Dr. Aylin Kaya",
    role: "Faculty",
    institution: "ClinMira Academic Network",
    program: "Restorative Dentistry",
    focusArea: "Scenario calibration",
    avatarInitials: "AK",
    unreadNotifications: 2,
  },
]

export const cases: Case[] = [
  {
    id: "acute-apical-abscess",
    title: "Severe mandibular pain and swelling",
    specialty: "Endodontics",
    difficulty: "Intermediate",
    durationMinutes: 34,
    targetCompetencies: ["Emergency diagnosis", "Clinical reasoning", "Communication", "Safety"],
    personaLabel: "Anxious patient",
    modalities: ["Chat", "Voice-ready", "Imaging", "Emergency"],
    status: "In progress",
    summary:
      "Severe mandibular pain, nocturnal worsening, localized swelling, and rising anxiety around dental treatment.",
    chiefComplaint: "My lower molar is throbbing and my face feels swollen.",
    hiddenDiagnosis: "Acute apical abscess associated with tooth 46",
    assignedToday: true,
    facultyApproved: true,
    coverAccent: "from-sky-500/25 via-cyan-500/8 to-transparent",
    stationLabel: "Emergency triage station",
    alerts: ["Antibiotic allergy hidden", "Red flag escalation possible"],
  },
  {
    id: "periodontal-disease-progression",
    title: "Progressive gum bleeding and tooth mobility",
    specialty: "Periodontology",
    difficulty: "Advanced",
    durationMinutes: 28,
    targetCompetencies: ["Treatment planning", "History taking", "Exam technique", "Communication"],
    personaLabel: "Low adherence patient",
    modalities: ["Chat", "OSCE", "Imaging"],
    status: "Not started",
    summary:
      "Case preview: Bleeding on brushing, halitosis, and worsening mobility under inconsistent periodontal recall.",
    chiefComplaint: "My gums keep bleeding and I think a tooth is getting loose.",
    hiddenDiagnosis: "Stage III periodontitis with localized mobility",
    assignedToday: true,
    facultyApproved: true,
    coverAccent: "from-cyan-500/18 via-slate-400/6 to-transparent",
    stationLabel: "Periodontal review bay",
    alerts: ["Smoking history hidden", "Mobility charting required"],
  },
  {
    id: "oral-leukoplakia-risk-assessment",
    title: "Persistent white oral patch",
    specialty: "Oral Pathology",
    difficulty: "OSCE-level",
    durationMinutes: 31,
    targetCompetencies: ["Risk assessment", "Clinical reasoning", "Safety", "Communication"],
    personaLabel: "Smoker, low health literacy",
    modalities: ["Chat", "Imaging", "OSCE"],
    status: "Not started",
    summary:
      "Case preview: Persistent non-scrapable white patch with smoking exposure and low referral readiness.",
    chiefComplaint: "This white patch on my cheek won't go away.",
    hiddenDiagnosis: "Leukoplakia with dysplasia risk requiring biopsy",
    assignedToday: true,
    facultyApproved: true,
    coverAccent: "from-violet-500/18 via-blue-500/8 to-transparent",
    stationLabel: "Lesion assessment room",
    alerts: ["Malignancy red flags hidden", "Biopsy timing scored"],
  },
  {
    id: "pediatric-trauma-case",
    title: "Child with dental trauma after fall",
    specialty: "Pediatric Dentistry",
    difficulty: "Intermediate",
    durationMinutes: 24,
    targetCompetencies: ["Emergency management", "Communication", "Safety", "Treatment planning"],
    personaLabel: "Pediatric patient",
    modalities: ["Chat", "Imaging", "Emergency"],
    status: "Not started",
    summary:
      "Case preview: Bleeding, distress, and uncertain injury history after a school fall require calm emergency triage.",
    chiefComplaint: "He fell at school and now his front tooth looks pushed back.",
    hiddenDiagnosis: "Luxation injury requiring urgent trauma protocol",
    assignedToday: false,
    facultyApproved: true,
    coverAccent: "from-sky-500/18 via-cyan-500/8 to-transparent",
    stationLabel: "Trauma simulation bay",
    alerts: ["Head injury screen hidden", "Parent communication graded"],
  },
  {
    id: "elderly-mci-medication-review",
    title: "Elderly patient with unclear symptoms",
    specialty: "General Dentistry",
    difficulty: "Advanced",
    durationMinutes: 36,
    targetCompetencies: ["History taking", "Safety", "Treatment planning", "Communication"],
    personaLabel: "Elderly poor historian",
    modalities: ["Chat", "OSCE", "Emergency"],
    status: "Not started",
    summary:
      "Case preview: Incomplete medical recall and subtle cognitive drift complicate urgent treatment planning.",
    chiefComplaint: "My daughter said I should get this sore tooth checked before it gets worse.",
    hiddenDiagnosis: "Symptomatic retained root with anticoagulant safety concern",
    assignedToday: true,
    facultyApproved: true,
    coverAccent: "from-slate-500/18 via-sky-500/6 to-transparent",
    stationLabel: "Geriatric consult pod",
    alerts: ["Medication reconciliation hidden", "Capacity cues present"],
  },
  {
    id: "endodontic-pain-differential",
    title: "Pain after deep restoration",
    specialty: "Endodontics",
    difficulty: "Intermediate",
    durationMinutes: 29,
    targetCompetencies: ["Differential diagnosis", "Clinical reasoning", "Exam technique", "Treatment planning"],
    personaLabel: "Worried patient",
    modalities: ["Chat", "Imaging", "OSCE"],
    status: "Not started",
    summary:
      "Case preview: Sharp biting pain, uncertain pulpal status, and a heavily restored posterior tooth.",
    chiefComplaint: "It hurts sharply when I bite and then let go.",
    hiddenDiagnosis: "Cracked tooth syndrome versus symptomatic apical periodontitis",
    assignedToday: true,
    facultyApproved: true,
    coverAccent: "from-blue-500/18 via-slate-400/8 to-transparent",
    stationLabel: "Endodontic differential lab",
    alerts: ["Test sequencing matters", "Premature diagnosis penalty"],
  },
  {
    id: "oral-ulcer-differential",
    title: "Recurrent painful oral ulcers",
    specialty: "Oral Medicine",
    difficulty: "Advanced",
    durationMinutes: 27,
    targetCompetencies: ["Diagnostic reasoning", "Safety", "Communication", "History taking"],
    personaLabel: "Stressed patient",
    modalities: ["Chat", "OSCE", "Imaging"],
    status: "Not started",
    summary:
      "Case preview: Recurrent ulceration with concerning duration and incomplete social-risk disclosure.",
    chiefComplaint: "This ulcer under my tongue keeps coming back and stings.",
    hiddenDiagnosis: "Traumatic ulcer versus malignancy requiring urgent review",
    assignedToday: false,
    facultyApproved: true,
    coverAccent: "from-violet-500/18 via-fuchsia-500/6 to-transparent",
    stationLabel: "Soft tissue review room",
    alerts: ["Cancer risk cues hidden", "Documentation weighted"],
  },
  {
    id: "medication-allergy-safety-case",
    title: "Medication reaction risk before procedure",
    specialty: "Patient Safety",
    difficulty: "OSCE-level",
    durationMinutes: 25,
    targetCompetencies: ["Safety checks", "Communication", "Time management", "Treatment planning"],
    personaLabel: "Incomplete medication recall",
    modalities: ["Chat", "Emergency", "OSCE"],
    status: "Completed",
    summary:
      "Case preview: The learner must clarify allergy and medication history before urgent prescribing decisions.",
    chiefComplaint: "I need something strong for this infection so I can get back to work.",
    hiddenDiagnosis: "Odontogenic infection with hidden penicillin allergy",
    assignedToday: false,
    facultyApproved: true,
    coverAccent: "from-amber-500/18 via-rose-500/5 to-transparent",
    stationLabel: "Urgent care consult",
    alerts: ["Allergy disclosure hidden", "Prescription shortcut trap"],
  },
  {
    id: "cbct-interpretation-training",
    title: "Complex implant planning review",
    specialty: "Radiology",
    difficulty: "Advanced",
    durationMinutes: 33,
    targetCompetencies: ["Imaging interpretation", "Clinical reasoning", "Safety", "Treatment planning"],
    personaLabel: "Calm patient",
    modalities: ["Imaging", "OSCE", "Chat"],
    status: "Not started",
    summary:
      "Case preview: Advanced imaging interpretation is required before higher-risk surgical planning.",
    chiefComplaint: "My surgeon said I needed more imaging before the implant plan.",
    hiddenDiagnosis: "CBCT interpretation training for anatomy-sensitive planning",
    assignedToday: true,
    facultyApproved: true,
    coverAccent: "from-indigo-500/18 via-cyan-500/8 to-transparent",
    stationLabel: "Imaging interpretation suite",
    alerts: ["Radiation stewardship scored", "Anatomy counseling required"],
  },
  {
    id: "dental-anxiety-patient",
    title: "Delayed treatment due to dental phobia",
    specialty: "Behavioral Dentistry",
    difficulty: "Beginner",
    durationMinutes: 22,
    targetCompetencies: ["Communication", "Time management", "History taking", "Safety"],
    personaLabel: "Phobic patient",
    modalities: ["Chat", "Voice-ready", "OSCE"],
    status: "Completed",
    summary:
      "Case preview: A patient repeatedly delays needed care and becomes guarded when treatment moves too quickly.",
    chiefComplaint: "I almost cancelled because I hate coming to the dentist.",
    hiddenDiagnosis: "Moderate caries with a major dental anxiety barrier",
    assignedToday: false,
    facultyApproved: true,
    coverAccent: "from-cyan-500/18 via-sky-500/8 to-transparent",
    stationLabel: "Behavioral communication suite",
    alerts: ["Rapport-sensitive", "Empathy scored heavily"],
  },
]

export const caseById = new Map(cases.map((item) => [item.id, item]))

export const patients: PatientTwin[] = [
  {
    id: "patient-acute-apical-abscess",
    caseId: "acute-apical-abscess",
    name: "Leyla Demir",
    age: 42,
    sex: "Female",
    avatarLabel: "LD",
    chiefComplaint: "Severe lower molar pain and swelling",
    painScore: 8,
    anxietyLevel: 74,
    trustLevel: 58,
    timerMinutesRemaining: 24,
    condition: "worsening",
    allergyStatus: "Unknown until asked",
    hiddenHistoryPrompt: "More history becomes available if you ask about duration, medications, and allergies.",
    medicalAlerts: ["Hypertension disclosed only after medication history is explored"],
    riskFlags: ["Spreading infection must be ruled out", "Antibiotic safety must be checked"],
    vitals: {
      bloodPressure: "128/82",
      heartRate: 96,
      temperatureC: 37.9,
      oxygenSat: 98,
    },
    history: {
      hpi: "Progressive pain, nocturnal worsening, and swelling for 48 hours.",
      pastMedicalHistory: "Hypertension, details incomplete.",
      medications: "Unknown antihypertensive.",
      allergies: "Possible antibiotic allergy, requires clarification.",
      socialHistory: "Avoids dental care due to anxiety.",
      dentalHistory: "Previous deep restoration on lower molar.",
    },
    exam: {
      extraoral: "Mild facial swelling.",
      intraoral: "Localized vestibular swelling near mandibular molar.",
      periodontal: "Within normal limits around involved tooth.",
      pulpTests: "Negative response on suspected tooth.",
      percussion: "Positive.",
      palpation: "Tender.",
      mobility: "Mild.",
      probingDepth: "Within normal limits around involved tooth.",
      softTissue: "No suspicious mucosal lesion; acute inflammatory swelling present.",
    },
    persona: {
      badge: "Anxious",
      emotionBaseline: "anxious",
      nonVerbalCues: [
        "Avoids eye contact.",
        "Holds left jaw while speaking.",
        "Hesitates before discussing medication history.",
        "Becomes calmer after empathetic communication.",
      ],
      communicationStyle: "Fast answers at first, then more cooperative with reassurance.",
      reliability: "reliable",
      healthLiteracy: "Moderate",
    },
  },
  {
    id: "patient-periodontal-disease-progression",
    caseId: "periodontal-disease-progression",
    name: "Mehmet Sari",
    age: 49,
    sex: "Male",
    avatarLabel: "MS",
    chiefComplaint: "My gums keep bleeding and I think a tooth is getting loose.",
    painScore: 4,
    anxietyLevel: 38,
    trustLevel: 62,
    timerMinutesRemaining: 28,
    condition: "stable",
    allergyStatus: "No known drug allergies reported",
    hiddenHistoryPrompt: "Smoking and recall compliance details need to be explored.",
    medicalAlerts: ["Smokes socially but minimizes frequency initially"],
    riskFlags: ["Recall non-adherence", "Tooth mobility risk"],
    vitals: {
      bloodPressure: "134/84",
      heartRate: 82,
      temperatureC: 36.8,
      oxygenSat: 99,
    },
    history: {
      hpi: "Bleeding worsened over six months with increasing halitosis and occasional soreness.",
      pastMedicalHistory: "Mild hypertension controlled with medication.",
      medications: "Amlodipine daily.",
      allergies: "None known.",
      socialHistory: "Occasional smoker with irregular hygiene habits during stressful work periods.",
      dentalHistory: "Lost regular periodontal maintenance follow-up after moving cities.",
    },
    exam: {
      extraoral: "No facial swelling or lymphadenopathy.",
      intraoral: "Generalized marginal erythema with localized recession and plaque accumulation.",
      periodontal: "Bleeding on probing with localized 6-7 mm pockets posteriorly.",
      pulpTests: "Vitality intact in affected region.",
      percussion: "No apical percussion pain.",
      palpation: "Mild gingival tenderness only.",
      mobility: "Grade I mobility on mandibular molar.",
      probingDepth: "Generalized 4-5 mm with localized deeper posterior pockets.",
      softTissue: "No ulcerative lesion.",
    },
    persona: {
      badge: "Poor historian",
      emotionBaseline: "calm",
      nonVerbalCues: [
        "Patient shrugs when asked about previous recall visits.",
        "Patient gives vague timing around symptom onset.",
      ],
      communicationStyle: "Conversational but imprecise.",
      reliability: "poor historian",
      healthLiteracy: "Moderate",
    },
  },
  {
    id: "patient-oral-leukoplakia-risk-assessment",
    caseId: "oral-leukoplakia-risk-assessment",
    name: "Fatma Celik",
    age: 58,
    sex: "Female",
    avatarLabel: "FC",
    chiefComplaint: "This white patch on my cheek won't go away.",
    painScore: 2,
    anxietyLevel: 41,
    trustLevel: 60,
    timerMinutesRemaining: 31,
    condition: "stable",
    allergyStatus: "No known allergy reported",
    hiddenHistoryPrompt: "Tobacco exposure and lesion duration need careful follow-up questions.",
    medicalAlerts: ["Patient is reluctant about biopsy referral"],
    riskFlags: ["Persistent lesion", "Potential dysplasia"],
    vitals: {
      bloodPressure: "126/78",
      heartRate: 76,
      temperatureC: 36.7,
      oxygenSat: 99,
    },
    history: {
      hpi: "Non-scrapable white lesion present for more than three months with no meaningful change.",
      pastMedicalHistory: "Hyperlipidemia.",
      medications: "Rosuvastatin nightly.",
      allergies: "No known allergies.",
      socialHistory: "Long-term smoking history initially minimized.",
      dentalHistory: "Irregular dental attendance, last oral medicine review several years ago.",
    },
    exam: {
      extraoral: "No significant extraoral findings.",
      intraoral: "Non-scrapable white plaque on buccal mucosa with slightly irregular margins.",
      periodontal: "Generalized mild chronic gingivitis only.",
      pulpTests: "Not clinically relevant for lesion-focused station.",
      percussion: "No percussion findings.",
      palpation: "No induration externally; internal palpation needs documentation.",
      mobility: "Normal tooth mobility.",
      probingDepth: "Within mild chronic gingivitis range.",
      softTissue: "Persistent leukoplakic lesion requiring risk assessment and biopsy planning.",
    },
    persona: {
      badge: "Low health literacy",
      emotionBaseline: "confused",
      nonVerbalCues: [
        "Patient looks uncertain when biopsy is mentioned.",
        "Patient asks if the patch can just be watched longer.",
      ],
      communicationStyle: "Needs clear, plain-language explanations.",
      reliability: "reliable",
      healthLiteracy: "Low",
    },
  },
  {
    id: "patient-dental-anxiety-patient",
    caseId: "dental-anxiety-patient",
    name: "Ece Yildiz",
    age: 32,
    sex: "Female",
    avatarLabel: "EY",
    chiefComplaint: "I almost cancelled because I hate coming to the dentist.",
    painScore: 3,
    anxietyLevel: 79,
    trustLevel: 48,
    timerMinutesRemaining: 22,
    condition: "stable",
    allergyStatus: "None known",
    hiddenHistoryPrompt: "Avoidance history needs gentle questioning.",
    medicalAlerts: ["High dental anxiety response"],
    riskFlags: ["Care avoidance", "Rapport-sensitive"],
    vitals: {
      bloodPressure: "122/76",
      heartRate: 88,
      temperatureC: 36.6,
      oxygenSat: 99,
    },
    history: {
      hpi: "Intermittent sensitivity and broken attendance due to fear of pain and judgment.",
      pastMedicalHistory: "Unremarkable.",
      medications: "No regular medications.",
      allergies: "No known allergies.",
      socialHistory: "Busy office schedule and heightened procedural anxiety.",
      dentalHistory: "Several delayed restorative appointments.",
    },
    exam: {
      extraoral: "No acute extraoral findings.",
      intraoral: "Localized carious lesion on posterior tooth with plaque retention.",
      periodontal: "Localized mild gingivitis.",
      pulpTests: "Within expected range for reversible sensitivity picture.",
      percussion: "Negative.",
      palpation: "Negative.",
      mobility: "Normal.",
      probingDepth: "Localized shallow pockets only.",
      softTissue: "No lesion noted.",
    },
    persona: {
      badge: "Anxious",
      emotionBaseline: "anxious",
      nonVerbalCues: [
        "Patient grips the chair arms during treatment discussion.",
        "Patient laughs nervously when asked why care was delayed.",
      ],
      communicationStyle: "Responsive to reassurance and shared-control language.",
      reliability: "reliable",
      healthLiteracy: "Moderate",
    },
  },
  {
    id: "patient-elderly-mci-medication-review",
    caseId: "elderly-mci-medication-review",
    name: "Huseyin Arslan",
    age: 74,
    sex: "Male",
    avatarLabel: "HA",
    chiefComplaint: "My daughter said I should get this sore tooth checked before it gets worse.",
    painScore: 5,
    anxietyLevel: 32,
    trustLevel: 63,
    timerMinutesRemaining: 36,
    condition: "stable",
    allergyStatus: "Unknown until medication reconciliation",
    hiddenHistoryPrompt: "Medication, anticoagulants, and caregiver context require structured questioning.",
    medicalAlerts: ["Mild cognitive impairment", "Polypharmacy concerns"],
    riskFlags: ["Capacity and consent cues", "Bleeding risk"],
    vitals: {
      bloodPressure: "138/80",
      heartRate: 79,
      temperatureC: 36.8,
      oxygenSat: 98,
    },
    history: {
      hpi: "Sore retained root area worsening over weeks with caregiver concern.",
      pastMedicalHistory: "Atrial fibrillation and mild cognitive impairment.",
      medications: "Apixaban, donepezil, and antihypertensives.",
      allergies: "Not reliably recalled without caregiver prompting.",
      socialHistory: "Lives with daughter who helps manage medications.",
      dentalHistory: "Missed several appointments due to transportation coordination.",
    },
    exam: {
      extraoral: "No swelling or trismus.",
      intraoral: "Retained root with localized inflammation and food packing.",
      periodontal: "Generalized recession and moderate plaque.",
      pulpTests: "Not applicable at retained root site.",
      percussion: "Localized tenderness.",
      palpation: "Mild localized tenderness.",
      mobility: "Adjacent teeth normal mobility.",
      probingDepth: "Generalized age-related periodontal loss.",
      softTissue: "No suspicious mucosal lesion.",
    },
    persona: {
      badge: "Elderly",
      emotionBaseline: "confused",
      nonVerbalCues: [
        "Patient pauses before recalling medications.",
        "Patient looks to family member when treatment details become complex.",
      ],
      communicationStyle: "Polite, slower answers, occasional memory gaps.",
      reliability: "confused",
      healthLiteracy: "Moderate",
    },
  },
  {
    id: "patient-pediatric-trauma-case",
    caseId: "pediatric-trauma-case",
    name: "Kerem Aydin",
    age: 9,
    sex: "Male",
    avatarLabel: "KA",
    chiefComplaint: "He fell at school and now his front tooth looks pushed back.",
    painScore: 7,
    anxietyLevel: 71,
    trustLevel: 52,
    timerMinutesRemaining: 24,
    condition: "stable",
    allergyStatus: "Unknown until parent confirms",
    hiddenHistoryPrompt: "Loss of consciousness and nausea history need to be screened carefully.",
    medicalAlerts: ["Parent distress influences pacing"],
    riskFlags: ["Trauma red flags", "Head injury screening"],
    vitals: {
      bloodPressure: "108/68",
      heartRate: 102,
      temperatureC: 36.9,
      oxygenSat: 99,
    },
    history: {
      hpi: "School fall 45 minutes ago with bleeding and apparent displacement of maxillary incisor.",
      pastMedicalHistory: "No chronic medical history reported.",
      medications: "None.",
      allergies: "Parent unsure about antibiotic exposures.",
      socialHistory: "Accompanied by worried parent.",
      dentalHistory: "Routine child dental care, no prior trauma.",
    },
    exam: {
      extraoral: "Mild upper lip swelling and superficial abrasions.",
      intraoral: "Traumatized maxillary incisor with displacement and gingival bleeding.",
      periodontal: "Localized trauma-related tenderness.",
      pulpTests: "Immediate vitality results may be unreliable post-trauma.",
      percussion: "Painful to percussion.",
      palpation: "Tender labial sulcus.",
      mobility: "Altered mobility pattern consistent with traumatic displacement.",
      probingDepth: "Not priority before trauma stabilization.",
      softTissue: "Minor lip laceration, no deep soft tissue deficit noted.",
    },
    persona: {
      badge: "Pediatric",
      emotionBaseline: "anxious",
      nonVerbalCues: [
        "Child clings to parent and speaks quietly.",
        "Parent answers quickly unless invited to pause.",
      ],
      communicationStyle: "Needs child-friendly, calm language.",
      reliability: "reliable",
      healthLiteracy: "Parent-mediated",
    },
  },
  {
    id: "patient-endodontic-pain-differential",
    caseId: "endodontic-pain-differential",
    name: "Selin Kurt",
    age: 35,
    sex: "Female",
    avatarLabel: "SK",
    chiefComplaint: "It hurts sharply when I bite and then let go.",
    painScore: 6,
    anxietyLevel: 44,
    trustLevel: 64,
    timerMinutesRemaining: 29,
    condition: "stable",
    allergyStatus: "No known allergy reported",
    hiddenHistoryPrompt: "Trigger patterns and previous temporary relief are important to explore.",
    medicalAlerts: ["Recent self-medication history"],
    riskFlags: ["Differential requires careful sequencing"],
    vitals: {
      bloodPressure: "118/74",
      heartRate: 80,
      temperatureC: 36.7,
      oxygenSat: 99,
    },
    history: {
      hpi: "Sharp pain on release of bite for one week with intermittent dull ache afterward.",
      pastMedicalHistory: "Unremarkable.",
      medications: "Ibuprofen as needed.",
      allergies: "No known allergies.",
      socialHistory: "Busy professional, delayed care until pain affected eating.",
      dentalHistory: "Large posterior restorations and occasional bruxism.",
    },
    exam: {
      extraoral: "No significant extraoral findings.",
      intraoral: "Restored posterior tooth with possible crack line under cusp.",
      periodontal: "No generalized periodontal breakdown.",
      pulpTests: "Equivocal vitality response requiring correlation.",
      percussion: "Mild to moderate response depending on cusp loading.",
      palpation: "Minimal soft tissue tenderness.",
      mobility: "Normal.",
      probingDepth: "Possible isolated narrow probing defect if crack extends.",
      softTissue: "No lesion noted.",
    },
    persona: {
      badge: "Reliable",
      emotionBaseline: "calm",
      nonVerbalCues: [
        "Patient points precisely to the biting phase that triggers pain.",
        "Patient becomes frustrated when symptoms are dismissed as minor sensitivity.",
      ],
      communicationStyle: "Detailed and precise.",
      reliability: "reliable",
      healthLiteracy: "High",
    },
  },
  {
    id: "patient-oral-ulcer-differential",
    caseId: "oral-ulcer-differential",
    name: "Zehra Inan",
    age: 46,
    sex: "Female",
    avatarLabel: "ZI",
    chiefComplaint: "This ulcer under my tongue keeps coming back and stings.",
    painScore: 5,
    anxietyLevel: 47,
    trustLevel: 55,
    timerMinutesRemaining: 27,
    condition: "stable",
    allergyStatus: "No known allergy reported",
    hiddenHistoryPrompt: "Tobacco exposure and duration require persistence to uncover fully.",
    medicalAlerts: ["Patient defensive about smoking history"],
    riskFlags: ["Persistent ulcer red flags"],
    vitals: {
      bloodPressure: "124/78",
      heartRate: 78,
      temperatureC: 36.7,
      oxygenSat: 99,
    },
    history: {
      hpi: "Ulcer intermittently painful over six weeks, not fully resolving.",
      pastMedicalHistory: "No major systemic disease disclosed.",
      medications: "Occasional topical analgesic gel.",
      allergies: "No known allergies.",
      socialHistory: "Tobacco exposure initially downplayed.",
      dentalHistory: "Irregular attendance with history of rough lingual tooth edge.",
    },
    exam: {
      extraoral: "No facial swelling.",
      intraoral: "Ulcer on ventrolateral tongue with erythematous halo.",
      periodontal: "Mild plaque-related gingivitis only.",
      pulpTests: "Not relevant to lesion station.",
      percussion: "Not relevant.",
      palpation: "Needs careful assessment for induration.",
      mobility: "Normal tooth mobility.",
      probingDepth: "Routine range.",
      softTissue: "Persistent ulcer with concerning duration.",
    },
    persona: {
      badge: "Defensive",
      emotionBaseline: "defensive",
      nonVerbalCues: [
        "Patient crosses arms when smoking is raised.",
        "Patient minimizes symptom duration initially.",
      ],
      communicationStyle: "Guarded until rapport improves.",
      reliability: "defensive",
      healthLiteracy: "Moderate",
    },
  },
  {
    id: "patient-medication-allergy-safety-case",
    caseId: "medication-allergy-safety-case",
    name: "Berk Gunes",
    age: 41,
    sex: "Male",
    avatarLabel: "BG",
    chiefComplaint: "I need something strong for this infection so I can get back to work.",
    painScore: 6,
    anxietyLevel: 52,
    trustLevel: 54,
    timerMinutesRemaining: 25,
    condition: "stable",
    allergyStatus: "Unknown until asked carefully",
    hiddenHistoryPrompt: "Medication expectations are clear, allergy history is not.",
    medicalAlerts: ["Allergy history incompletely volunteered"],
    riskFlags: ["Unsafe prescription shortcut"],
    vitals: {
      bloodPressure: "130/80",
      heartRate: 86,
      temperatureC: 37.4,
      oxygenSat: 99,
    },
    history: {
      hpi: "Pain and swelling for two days with strong preference for a quick prescription.",
      pastMedicalHistory: "No major chronic disease stated.",
      medications: "Occasional OTC pain medication.",
      allergies: "Prior penicillin reaction only disclosed if specifically asked.",
      socialHistory: "Time pressure and low tolerance for long explanations.",
      dentalHistory: "Intermittent urgent care only.",
    },
    exam: {
      extraoral: "Localized swelling without airway concern.",
      intraoral: "Acute inflammation at lower posterior site.",
      periodontal: "Localized inflammation only.",
      pulpTests: "Likely necrotic source tooth.",
      percussion: "Positive.",
      palpation: "Positive in vestibule.",
      mobility: "Within expected range.",
      probingDepth: "No major periodontal pocketing.",
      softTissue: "Inflamed vestibular tissues.",
    },
    persona: {
      badge: "Low health literacy",
      emotionBaseline: "defensive",
      nonVerbalCues: [
        "Patient interrupts to ask for antibiotics early.",
        "Patient seems impatient when questioned about past reactions.",
      ],
      communicationStyle: "Blunt and time-pressured.",
      reliability: "poor historian",
      healthLiteracy: "Low",
    },
  },
  {
    id: "patient-cbct-interpretation-training",
    caseId: "cbct-interpretation-training",
    name: "Deniz Acar",
    age: 23,
    sex: "Female",
    avatarLabel: "DA",
    chiefComplaint: "My wisdom tooth surgeon said I needed extra imaging before the extraction.",
    painScore: 2,
    anxietyLevel: 35,
    trustLevel: 66,
    timerMinutesRemaining: 33,
    condition: "stable",
    allergyStatus: "No known allergy reported",
    hiddenHistoryPrompt: "Surgical expectations and nerve-risk counseling should be explored.",
    medicalAlerts: ["Radiation stewardship is part of the station"],
    riskFlags: ["Inferior alveolar nerve proximity"],
    vitals: {
      bloodPressure: "116/72",
      heartRate: 74,
      temperatureC: 36.6,
      oxygenSat: 99,
    },
    history: {
      hpi: "Intermittent wisdom tooth discomfort with referral for imaging before extraction.",
      pastMedicalHistory: "Unremarkable.",
      medications: "None.",
      allergies: "No known allergies.",
      socialHistory: "University student seeking to schedule surgery during break.",
      dentalHistory: "Previously advised extraction due to recurrent pericoronitis.",
    },
    exam: {
      extraoral: "No swelling or asymmetry.",
      intraoral: "Partially erupted mandibular third molar with pericoronal irritation history.",
      periodontal: "Localized pericoronal inflammation risk only.",
      pulpTests: "Not focus of station.",
      percussion: "Not significant.",
      palpation: "Mild distal tenderness.",
      mobility: "Not significant.",
      probingDepth: "Distal pocketing around impacted third molar.",
      softTissue: "Localized pericoronal irritation.",
    },
    persona: {
      badge: "Reliable",
      emotionBaseline: "calm",
      nonVerbalCues: [
        "Patient looks relieved when risks are explained clearly.",
        "Patient asks specifically about nerve injury and recovery.",
      ],
      communicationStyle: "Engaged and detail-oriented.",
      reliability: "reliable",
      healthLiteracy: "High",
    },
  },
]

export const patientByCaseId = new Map(patients.map((item) => [item.caseId, item]))

export const orderCatalog: ClinicalOrder[] = [
  {
    id: "periapical-radiograph",
    name: "Periapical radiograph",
    costLevel: "Low",
    timeDelay: "2 min",
    riskLevel: "Low radiation",
    educationalRelevance: "Foundational first-line imaging for periapical and endodontic reasoning.",
  },
  {
    id: "panoramic-radiograph",
    name: "Panoramic radiograph",
    costLevel: "Medium",
    timeDelay: "Short delay",
    riskLevel: "Low radiation",
    educationalRelevance: "Useful for wider anatomical overview and pathology screening.",
  },
  {
    id: "cbct",
    name: "CBCT",
    costLevel: "High",
    timeDelay: "10 min",
    riskLevel: "Higher radiation",
    educationalRelevance: "Advanced imaging reserved for specific indications and anatomy-sensitive planning.",
  },
  {
    id: "cbc",
    name: "CBC",
    costLevel: "Medium",
    timeDelay: "Delayed",
    riskLevel: "Blood draw",
    educationalRelevance: "Supports infection and systemic review in selected cases.",
  },
  {
    id: "crp",
    name: "CRP",
    costLevel: "Medium",
    timeDelay: "Delayed",
    riskLevel: "Blood draw",
    educationalRelevance: "Adjunct inflammatory marker for systemic concern scenarios.",
  },
  {
    id: "vitality-test",
    name: "Vitality test",
    costLevel: "Low",
    timeDelay: "3 min",
    riskLevel: "No radiation",
    educationalRelevance: "Core endodontic differential input.",
  },
  {
    id: "biopsy",
    name: "Biopsy",
    costLevel: "High",
    timeDelay: "Referral dependent",
    riskLevel: "Invasive procedure",
    educationalRelevance: "Definitive tissue diagnosis for suspicious lesions.",
  },
  {
    id: "culture",
    name: "Culture",
    costLevel: "Moderate",
    timeDelay: "24 hr",
    riskLevel: "Sample collection",
    educationalRelevance: "Selective microbiology support rather than routine first-line testing.",
  },
]

export const imagingData: Record<string, ImagingStudy[]> = {
  "acute-apical-abscess": [
    {
      id: "img-acute-pa",
      label: "Periapical reference view",
      type: "Periapical",
      viewHint: "Periapical shadowing at the apex of tooth 46 with widened periodontal ligament space.",
      findings: [
        "Periapical radiolucency associated with tooth 46.",
        "Restoration approaching pulp chamber.",
        "No generalized bone loss pattern.",
      ],
      annotations: ["Apical radiolucency marker", "Restoration margin", "Faculty reference anchor"],
      watermark: "Synthetic educational image",
      approved: true,
      agentStatus: "Imaging Agent generated validated teaching image",
    },
    {
      id: "img-acute-cbct",
      label: "CBCT exploratory volume",
      type: "CBCT",
      viewHint: "Cortical expansion and local inflammatory spread can be explored when escalation is justified.",
      findings: [
        "Localized cortical thinning buccally near tooth 46.",
        "No deep fascial spread demonstrated in this teaching set.",
      ],
      annotations: ["Buccal cortical outline", "Inflammatory zone overlay"],
      watermark: "Synthetic educational image",
      approved: true,
      agentStatus: "Imaging Agent waiting for indication review",
    },
  ],
  "cbct-interpretation-training": [
    {
      id: "img-cbct-1",
      label: "Mandibular third molar CBCT",
      type: "CBCT",
      viewHint: "Review inferior alveolar canal relationship in coronal and sagittal planes.",
      findings: [
        "Close approximation of impacted 48 roots to the inferior alveolar canal.",
        "Lingual cortical thinning without frank perforation.",
      ],
      annotations: ["Nerve canal outline", "Root apex relation", "Faculty nerve-risk note"],
      watermark: "Synthetic educational image",
      approved: true,
      agentStatus: "Imaging Agent generated high-risk anatomy teaching volume",
    },
  ],
}

export const baseAgents: Agent[] = [
  {
    id: "persona-agent",
    name: "Persona Agent",
    role: "Patient communication, emotion, uncertainty, anxiety.",
    status: "generating",
    confidence: 94,
    latencyMs: 560,
    validationStatus: "Approved",
    warnings: [],
    lastAction: "Adjusted anxiety after rushed communication.",
  },
  {
    id: "physiology-agent",
    name: "Physiology Agent",
    role: "Symptoms, vitals, disease progression, clinical consistency.",
    status: "validating",
    confidence: 96,
    latencyMs: 640,
    validationStatus: "Approved",
    warnings: [],
    lastAction: "Watched swelling progression and systemic red flags.",
  },
  {
    id: "imaging-agent",
    name: "Imaging Agent",
    role: "Synthetic radiograph and CBCT simulation.",
    status: "idle",
    confidence: 91,
    latencyMs: 720,
    validationStatus: "Queued",
    warnings: ["Advanced imaging should follow first-line indication logic."],
    lastAction: "Prepared synthetic periapical view.",
  },
  {
    id: "evaluator-agent",
    name: "Evaluator Agent",
    role: "Scores diagnosis, reasoning, treatment, communication.",
    status: "thinking",
    confidence: 93,
    latencyMs: 590,
    validationStatus: "Approved",
    warnings: [],
    lastAction: "Updated clinical reasoning score.",
  },
  {
    id: "safety-agent",
    name: "Safety Agent",
    role: "Flags unsafe medication, missed allergies, red flags.",
    status: "warning",
    confidence: 98,
    latencyMs: 610,
    validationStatus: "Guardrails active",
    warnings: ["Allergy check not yet confirmed in current emergency station."],
    lastAction: "Blocked antibiotic recommendation before allergy clarification.",
  },
  {
    id: "faculty-review-agent",
    name: "Faculty Review Agent",
    role: "Routes uncertain outputs for instructor approval.",
    status: "idle",
    confidence: 89,
    latencyMs: 600,
    validationStatus: "Ready",
    warnings: [],
    lastAction: "Added image output to review queue.",
  },
]

export const initialTimelineByCaseId: Record<string, TimelineEvent[]> = {
  "acute-apical-abscess": [
    {
      id: "tl-acute-0",
      type: "question",
      title: "Asked chief complaint",
      description: "Encounter opened with severe lower molar pain and visible swelling.",
      timestamp: "00:20",
    },
    {
      id: "tl-acute-1",
      type: "warning",
      title: "Patient anxiety increased",
      description: "The patient twin became more guarded when the opening felt rushed.",
      timestamp: "01:15",
    },
    {
      id: "tl-acute-2",
      type: "question",
      title: "Pain duration explored",
      description: "The learner confirmed five days of pain with overnight worsening.",
      timestamp: "02:10",
    },
    {
      id: "tl-acute-3",
      type: "warning",
      title: "Allergy clarification missed",
      description: "Safety Guardrail flagged incomplete allergy review before treatment planning.",
      timestamp: "03:05",
    },
    {
      id: "tl-acute-4",
      type: "order",
      title: "Periapical radiograph ordered",
      description: "First-line imaging was requested before escalation.",
      timestamp: "04:20",
    },
    {
      id: "tl-acute-5",
      type: "exam",
      title: "Percussion test performed",
      description: "Positive percussion supported an odontogenic infection differential.",
      timestamp: "05:40",
    },
    {
      id: "tl-acute-6",
      type: "diagnosis",
      title: "Differential diagnosis submitted",
      description: "Acute apical abscess moved to the top of the working differential.",
      timestamp: "07:15",
    },
    {
      id: "tl-acute-7",
      type: "warning",
      title: "Safety Agent flagged allergy risk",
      description: "Treatment submission paused until allergy status and red flags were reviewed.",
      timestamp: "08:30",
    },
    {
      id: "tl-acute-8",
      type: "treatment",
      title: "Treatment plan revised",
      description: "The plan was updated after allergy clarification and safety review.",
      timestamp: "10:00",
    },
  ],
}

export const agentEvents: AgentEvent[] = [
  {
    id: "ae-1",
    title: "Persona Agent",
    description: "Patient anxiety decreased after empathetic response.",
    severity: "info",
    timestamp: "14:03",
  },
  {
    id: "ae-2",
    title: "Safety Agent",
    description: "Blocked treatment plan until allergy review.",
    severity: "warning",
    timestamp: "14:06",
  },
  {
    id: "ae-3",
    title: "Imaging Agent",
    description: "Prepared faculty-approved periapical view.",
    severity: "success",
    timestamp: "14:08",
  },
  {
    id: "ae-4",
    title: "Evaluator Agent",
    description: "Updated clinical reasoning score.",
    severity: "success",
    timestamp: "14:10",
  },
  {
    id: "ae-5",
    title: "Faculty Review Agent",
    description: "Queued synthetic image for validation.",
    severity: "success",
    timestamp: "14:12",
  },
]

export const blockedOutputs = [
  "Antibiotic recommendation without allergy clarification.",
  "CBCT request without basic imaging rationale.",
  "Final diagnosis submitted before red-flag screening.",
]

export const facultyReviewQueue = [
  "Acute swelling replay awaiting faculty validation.",
  "Persistent white oral patch scenario awaiting sign-off.",
  "Synthetic periapical image awaiting review.",
  "Scenario rubric update awaiting approval.",
]

export const dashboardSkillProgress: SkillProgress[] = [
  { competency: "Clinical reasoning", current: 84, target: 92 },
  { competency: "Communication", current: 90, target: 93 },
  { competency: "Diagnostic accuracy", current: 79, target: 90 },
  { competency: "Treatment planning", current: 82, target: 91 },
  { competency: "Safety", current: 78, target: 95 },
  { competency: "Time management", current: 76, target: 88 },
]

export const dashboardRadarData = dashboardSkillProgress.map((item) => ({
  competency: item.competency,
  score: item.current,
  benchmark: item.target,
}))

export const recentPerformanceSeries = [
  { label: "Week 1", score: 72, trust: 68 },
  { label: "Week 2", score: 76, trust: 71 },
  { label: "Week 3", score: 81, trust: 75 },
  { label: "Week 4", score: 84, trust: 80 },
]

export const recentPerformanceTimeline = [
  {
    time: "Today",
    title: "Emergency pain encounter improved sequencing",
    detail: "You delayed treatment until after history clarification and first-line imaging review.",
    score: "+8 reasoning",
  },
  {
    time: "Yesterday",
    title: "Faculty note praised rapport recovery",
    detail: "You repaired trust after an initially rushed opening question in a communication-heavy case.",
    score: "+6 communication",
  },
  {
    time: "Mon",
    title: "Safety gap remains in medication shortcuts",
    detail: "Allergy confirmation still arrives later than ideal in urgent infection scenarios.",
    score: "-4 safety",
  },
]

export const activeSimulations = [
  "Severe mandibular pain and swelling",
  "Complex implant planning review",
]

export const criticalImprovementAreas = [
  "Improve allergy checks before treatment decisions.",
  "Strengthen differential diagnosis before imaging escalation.",
  "Tighten treatment safety review in urgent cases.",
]

export const facultyFeedback = {
  summary: "Faculty note: Review red-flag screening before emergency cases. Allergy and medication checks should happen earlier.",
  reviewer: "Dr. Aylin Kaya",
}

export const caseFilterOptions = {
  specialties: ["All specialties", "Dental", "Oral Pathology", "Endodontics", "Periodontology", "Emergency", "Pediatric Dentistry", "Radiology"],
  difficulties: ["All difficulties", "Beginner", "Intermediate", "OSCE-level", "Advanced"],
  durations: ["Any duration", "< 25 min", "25-30 min", "> 30 min"],
  competencies: [
    "All competencies",
    "Clinical reasoning",
    "Communication",
    "Diagnostic accuracy",
    "Treatment planning",
    "Safety",
    "Time management",
    "Imaging interpretation",
    "History taking",
    "Exam technique",
    "Emergency triage",
  ],
  personas: ["All personas", "Anxious", "Elderly", "Pediatric", "Poor historian", "Low health literacy", "Reliable", "Defensive"],
  modalities: ["All modalities", "Chat", "Voice-ready", "Imaging", "OSCE", "Emergency"],
  statuses: ["All statuses", "Not started", "In progress", "Completed"],
}

export const facultyMetrics: FacultyMetric[] = [
  { label: "Total Students", value: "128", change: "7 need review", trend: "up" },
  { label: "Active Simulations", value: "34", change: "12 high-risk alerts", trend: "up" },
  { label: "Average Score", value: "81%", change: "+3 this month", trend: "up" },
  { label: "Completion Rate", value: "89%", change: "Steady across cohorts", trend: "neutral" },
]

export const facultyCompetencyData = [
  { name: "Reasoning", cohort: 81, target: 90 },
  { name: "Safety", cohort: 77, target: 93 },
  { name: "Communication", cohort: 88, target: 92 },
  { name: "Imaging", cohort: 80, target: 89 },
  { name: "Planning", cohort: 83, target: 91 },
]

export const facultyImprovementData = [
  { month: "Jan", score: 74, completions: 68 },
  { month: "Feb", score: 77, completions: 72 },
  { month: "Mar", score: 79, completions: 78 },
  { month: "Apr", score: 81, completions: 84 },
  { month: "May", score: 82, completions: 91 },
]

export const facultyDistributionData = [
  { name: "OSCE-ready", value: 44 },
  { name: "Developing", value: 38 },
  { name: "Needs review", value: 18 },
]

export const facultyHeatmap = [
  { student: "M. Demir", reasoning: 74, safety: 71, communication: 82, imaging: 69 },
  { student: "E. Kaya", reasoning: 88, safety: 80, communication: 90, imaging: 84 },
  { student: "S. Aras", reasoning: 77, safety: 73, communication: 79, imaging: 81 },
  { student: "L. Yalcin", reasoning: 69, safety: 68, communication: 75, imaging: 70 },
]

export const topStrugglingStudents = [
  { name: "Lina Yalcin", area: "Needs earlier allergy clarification in urgent infection cases.", risk: "High" },
  { name: "Mert Demir", area: "Uses CBCT before first-line imaging rationale is complete.", risk: "Moderate" },
  { name: "Sila Aras", area: "Misses lesion red flags and systemic screening prompts.", risk: "Moderate" },
]

export const commonMissedQuestions = [
  "Medication allergy",
  "Current medications",
  "Fever or swelling progression",
  "Difficulty swallowing",
  "Previous dental treatment",
  "Medical contraindications",
]

export const recentSubmissions = [
  { caseTitle: "Severe mandibular pain and swelling", student: "Mohammad M.", score: 82, time: "14 min ago" },
  { caseTitle: "Complex implant planning review", student: "Elif T.", score: 88, time: "38 min ago" },
  { caseTitle: "Delayed treatment due to dental phobia", student: "Can G.", score: 91, time: "1 hr ago" },
]

export const facultyAlerts = [
  "7 students prescribed before allergy clarification.",
  "5 students overused CBCT in first-line assessment.",
  "11 students missed systemic infection screening.",
  "3 cases require faculty validation before publishing.",
]

const acuteRubric: RubricItem[] = [
  {
    label: "History taking",
    feedback: "Pain duration and progression were reviewed, but allergy and medication history came too late.",
    score: 8,
    maxScore: 10,
    emphasis: "warning",
  },
  {
    label: "Exam and investigation",
    feedback: "Percussion and first-line imaging were used appropriately before escalation.",
    score: 9,
    maxScore: 10,
    emphasis: "normal",
  },
  {
    label: "Diagnosis",
    feedback: "The differential narrowed correctly after the key endodontic findings were gathered.",
    score: 8,
    maxScore: 10,
    emphasis: "normal",
  },
  {
    label: "Treatment safety",
    feedback: "Prescribing logic improved after review, but the allergy check should have happened earlier.",
    score: 7,
    maxScore: 10,
    emphasis: "warning",
  },
  {
    label: "Communication",
    feedback: "Empathetic phrasing reduced anxiety and improved trust during the encounter.",
    score: 9,
    maxScore: 10,
    emphasis: "normal",
  },
]

const acuteCorrectPath: ReasoningNode[] = [
  { id: "r1", stage: "Symptom", label: "Pain progression", detail: "Severe lower molar pain worsened over several days." },
  { id: "r2", stage: "Evidence", label: "Swelling and percussion positive", detail: "Exam findings pointed to an urgent odontogenic source." },
  { id: "r3", stage: "Evidence", label: "Negative pulp response and periapical change", detail: "Vitality testing and imaging supported apical involvement." },
  { id: "r4", stage: "Diagnosis", label: "Acute odontogenic infection risk", detail: "The differential narrowed toward acute apical abscess.", tone: "success" },
  { id: "r5", stage: "Treatment", label: "Emergency management plan", detail: "Treatment required source control, red-flag review, and allergy-safe prescribing.", tone: "success" },
]

const acuteUserPath: ReasoningNode[] = [
  { id: "u1", stage: "Symptom", label: "Pain and swelling recognized", detail: "The urgent presentation was identified early." },
  { id: "u2", stage: "Evidence", label: "Allergy clarification delayed", detail: "Safety questions lagged behind the clinical assessment.", tone: "warning" },
  { id: "u3", stage: "Hypothesis", label: "Abscess suspected early", detail: "The main diagnosis was directionally correct before the evidence trail was complete.", tone: "warning" },
  { id: "u4", stage: "Diagnosis", label: "Acute apical abscess", detail: "The final diagnosis was accurate after first-line findings were reviewed.", tone: "success" },
  { id: "u5", stage: "Treatment", label: "Treatment plan revised after Safety Guardrail warning", detail: "The final plan improved once prescribing risk and red flags were revisited.", tone: "danger" },
]

export const debriefReports: Record<string, DebriefReport> = {
  "acute-apical-abscess": {
    caseId: "acute-apical-abscess",
    overallScore: 82,
    caseOutcome: "The patient twin remained clinically stable after the plan was revised for allergy and red-flag safety.",
    diagnosisAccuracy: 86,
    treatmentSafety: 74,
    communicationQuality: 90,
    timeEfficiency: 80,
    clinicalReasoning: 84,
    patientTrustFinal: 78,
    safetyScore: 76,
    strengths: [
      "Asked about pain duration and progression.",
      "Ordered appropriate first-line imaging.",
      "Recognized swelling as a risk indicator.",
      "Used empathetic communication to reduce anxiety.",
    ],
    criticalMisses: [
      "Allergy status was not clarified early.",
      "Medication history remained incomplete.",
      "Antibiotic planning was considered before full safety review.",
      "Systemic red flags were checked late.",
    ],
    unsafeActions: [
      "Prescribing before allergy clarification.",
      "Considering CBCT before basic radiograph.",
      "Delayed recognition of spreading infection risk.",
    ],
    missedQuestions: [
      "Do you have fever or difficulty swallowing?",
      "Do you have any medication allergies?",
      "Are you taking any medications?",
      "Have you had dental treatment on this tooth before?",
    ],
    correctReasoningPath: acuteCorrectPath,
    userReasoningPath: acuteUserPath,
    timelineReplay: initialTimelineByCaseId["acute-apical-abscess"],
    facultyRubric: acuteRubric,
    suggestedNextCaseIds: [
      "medication-allergy-safety-case",
      "endodontic-pain-differential",
      "dental-anxiety-patient",
    ],
    replayMistakes: [
      {
        title: "You prescribed before checking allergy",
        detail: "Treatment planning moved ahead of allergy clarification and full medication review.",
        impact: "This creates a high-risk prescribing error in an urgent care scenario.",
      },
      {
        title: "You considered CBCT before basic imaging",
        detail: "Advanced imaging was weighed before first-line radiography and examination were fully exhausted.",
        impact: "This adds cost and radiation without improving the first diagnostic step.",
      },
      {
        title: "You delayed systemic red-flag screening",
        detail: "Questions about spreading infection and systemic symptoms came later than ideal.",
        impact: "This can delay escalation when emergency management is needed.",
      },
    ],
  },
}

export function buildFallbackDebriefReport(caseId: string): DebriefReport {
  const caseItem = caseById.get(caseId) ?? cases[0]
  const fallbackPath: ReasoningNode[] = [
    { id: "f1", stage: "Symptom", label: caseItem.chiefComplaint, detail: "Primary symptom recognized." },
    { id: "f2", stage: "Evidence", label: "History and exam findings", detail: "Evidence trail gathered during the simulation." },
    { id: "f3", stage: "Hypothesis", label: "Working differential created", detail: "Learner narrowed hypotheses based on the available data." },
    { id: "f4", stage: "Diagnosis", label: "Provisional diagnosis submitted", detail: "Final diagnosis compared against hidden faculty answer." },
    { id: "f5", stage: "Treatment", label: "Treatment plan documented", detail: "Safety checklist and patient instructions were assessed." },
  ]

  return {
    caseId,
    overallScore: 82,
    caseOutcome: "This mock debrief reflects a solid encounter with remaining room to improve safety sequencing and explicit evidence documentation.",
    diagnosisAccuracy: 84,
    treatmentSafety: 79,
    communicationQuality: 88,
    timeEfficiency: 80,
    clinicalReasoning: 83,
    patientTrustFinal: 78,
    safetyScore: 80,
    strengths: [
      "Maintained a coherent patient-centered encounter.",
      "Used enough evidence to arrive at a defensible working diagnosis.",
    ],
    criticalMisses: ["A key hidden-history element was surfaced later than optimal."],
    unsafeActions: ["A minor sequencing risk was detected by the Safety Agent."],
    missedQuestions: ["One additional red-flag follow-up would have strengthened the case."],
    correctReasoningPath: fallbackPath,
    userReasoningPath: fallbackPath,
    timelineReplay: initialTimelineByCaseId[caseId] ?? initialTimelineByCaseId["acute-apical-abscess"],
    facultyRubric: acuteRubric,
    suggestedNextCaseIds: cases.slice(0, 3).map((item) => item.id),
    replayMistakes: [
      {
        title: "Evidence trail could be cleaner",
        detail: "The learner reached a workable answer, but the supporting sequence can still be sharpened.",
        impact: "Cleaner reasoning improves faculty defensibility and OSCE scoring.",
      },
    ],
  }
}

export const scenarioBuilderSteps = [
  "Scenario Basics",
  "Patient Profile",
  "Clinical Core",
  "Orders & Imaging",
  "Rubric",
  "Agent Configuration",
  "Review & Publish",
]

export const scenarioDraftConfig: ScenarioDraft = {
  title: "Acute mandibular swelling with urgent endodontic decision",
  specialty: "Endodontics",
  difficulty: "Intermediate",
  estimatedDuration: 30,
  learningObjectives: [
    "Identify red flags in odontogenic infection.",
    "Sequence history, exam, and imaging appropriately.",
    "Protect against unsafe prescribing.",
  ],
  patientProfile: {
    age: 42,
    sex: "Female",
    background: "Delayed care because of anxiety and now presents with swelling and incomplete medication recall.",
    healthLiteracy: "Moderate",
    anxietyLevel: "High",
    communicationStyle: "Guarded at first, calmer after empathy",
    personaType: "Anxious patient",
    reliability: "Incomplete medication recall",
  },
  clinicalCore: {
    chiefComplaint: "Severe lower molar pain and swelling",
    hiddenDiagnosis: "Acute apical abscess",
    differentialDiagnoses: [
      "Acute apical abscess",
      "Symptomatic apical periodontitis",
      "Periodontal abscess",
      "Cracked tooth syndrome",
    ],
    redFlags: ["Spreading swelling", "Difficulty swallowing", "Fever", "Systemic malaise"],
    contraindications: ["Prescribing without allergy clarification", "Ignoring systemic infection signs"],
    symptomProgressionRules: [
      "Anxiety rises if the learner sounds rushed.",
      "Trust improves after empathetic communication.",
      "Condition worsens if unsafe treatment is submitted.",
    ],
    dangerousActions: ["Prescribing before allergy check", "Escalating to CBCT before basic imaging"],
  },
  ordersAndImaging: {
    availableTests: [
      "Periapical radiograph",
      "Panoramic radiograph",
      "CBCT",
      "CBC",
      "CRP",
      "Vitality test",
    ],
    expectedResults: ["Periapical radiolucency suspected", "Negative pulp response", "Localized inflammatory swelling"],
    imagingType: "Synthetic educational radiograph with optional escalated CBCT teaching set",
    facultyApprovalRequired: true,
    syntheticImageMode: true,
  },
  rubric: acuteRubric,
  agentConfiguration: {
    personaStrictness: 92,
    physiologicalConsistency: 95,
    imagingGenerationMode: "Faculty-approved synthetic teaching output",
    evaluatorStrictness: 88,
    safetyGuardrailLevel: 97,
  },
}
